#ifndef __COMMAND_CONSTANTS_H__
#define __COMMAND_CONSTANTS_H__

#define MENU_ITEM_SELECTED 'mnu'
#define COLUMN_SET_SHOWN '001'
#define FILE_NAME_PATTERN_CHANGED '003'
#define MSG_ARTIST_CB '004'
#define MSG_ALBUM_CB '005'
#define MSG_TITLE_CB '006'
#define MSG_YEAR_CB '007'
#define MSG_COMMENT_CB '010'
#define MSG_TRACK_CB '011'
#define MSG_GENRE_CB '012'
#define GENRE_SEL_CHNGD '013'
#define ENCODE_MSG '014'
#define CANCEL_MSG '015'
#define APPLY_MSG '016'
#define LIST_SELECTION_MSG '017'
#define APPLY_ATTRIBUTE_CHANGES '020'
#define SELECT_ALL_MSG '021'
#define DESELECT_ALL_MSG '022'
#define REMOVE_MSG '023'
#define LIST_MSG '024'
#define ENCODER_CHANGED '025'
#define VIEW_SHORTCUT '026'

#define NUM_OF_COLUMNS 10
#define COMPLETE_COLUMN_INDEX 0
#define FILE_COLUMN_INDEX 1
#define SAVE_AS_COLUMN_INDEX 2
#define ARTIST_COLUMN_INDEX 3
#define ALBUM_COLUMN_INDEX 4
#define TITLE_COLUMN_INDEX 5
#define YEAR_COLUMN_INDEX 6
#define COMMENT_COLUMN_INDEX 7
#define TRACK_COLUMN_INDEX 8
#define GENRE_COLUMN_INDEX 9

#endif
