install:
	$(MAKE) --directory=./AEEncoder install
	$(MAKE) --directory=./FlipSideAE install
	$(MAKE) --directory=./BeEncoder install
	$(MAKE) --directory=./MP3GoGo install
	$(MAKE) --directory=./MP3Lame install
	$(MAKE) --directory=./OGGEncoder install
	$(MAKE) --directory=./M3UCreator install

release_clean:
	$(MAKE) --directory=./AEEncoder release_clean
	$(MAKE) --directory=./FlipSideAE release_clean
	$(MAKE) --directory=./BeEncoder release_clean
	$(MAKE) --directory=./MP3GoGo release_clean
	$(MAKE) --directory=./MP3Lame release_clean
	$(MAKE) --directory=./OGGEncoder release_clean
	$(MAKE) --directory=./M3UCreator release_clean

clean:
	$(MAKE) --directory=./AEEncoder clean
	$(MAKE) --directory=./FlipSideAE clean
	$(MAKE) --directory=./BeEncoder clean
	$(MAKE) --directory=./MP3GoGo clean
	$(MAKE) --directory=./MP3Lame clean
	$(MAKE) --directory=./OGGEncoder clean
	$(MAKE) --directory=./M3UCreator clean

release:
	$(MAKE) --directory=./AEEncoder release
	$(MAKE) --directory=./FlipSideAE release
	$(MAKE) --directory=./BeEncoder release
	$(MAKE) --directory=./MP3GoGo release
	$(MAKE) --directory=./MP3Lame release
	$(MAKE) --directory=./OGGEncoder release
	$(MAKE) --directory=./M3UCreator release

cleansettings :
	rm -rf /boot/home/config/settings/FlipSide\ Software/$(NAME)
