army:
	$(MAKE) --directory=./String/ install
	$(MAKE) --directory=./Matcher/ install
	$(MAKE) --directory=./Santa/ install
	$(MAKE) --directory=./ArmyKnife/ install

install:
	$(MAKE) --directory=./String/ install
	$(MAKE) --directory=./Matcher/ install
	$(MAKE) --directory=./AudioInfo/ install
	$(MAKE) --directory=./Santa/ install
	$(MAKE) --directory=./ArmyKnife/ install
	$(MAKE) --directory=./FlipSideAE/ install
	$(MAKE) --directory=./AudioInfo/ --makefile=MakefileTTE release
	$(MAKE) --directory=./ArmyKnife/ --makefile=MakefileTTE release

clean:
	$(MAKE) --directory=./String/ clean
	$(MAKE) --directory=./Matcher/ clean
	$(MAKE) --directory=./AudioInfo/ clean
	$(MAKE) --directory=./Santa/ clean
	$(MAKE) --directory=./ArmyKnife/ clean
	$(MAKE) --directory=./FlipSideAE/ clean
	$(MAKE) --directory=./AudioInfo/ --makefile=MakefileTTE clean
	$(MAKE) --directory=./ArmyKnife/ --makefile=MakefileTTE clean

release:
	$(MAKE) --directory=./String/ release
	$(MAKE) --directory=./Matcher/ release
	$(MAKE) --directory=./AudioInfo/ release
	$(MAKE) --directory=./Santa/ release
	$(MAKE) --directory=./ArmyKnife/ release
	$(MAKE) --directory=./FlipSideAE/ release
	$(MAKE) --directory=./AudioInfo/ --makefile=MakefileTTE release
	$(MAKE) --directory=./ArmyKnife/ --makefile=MakefileTTE release

release_clean:
	$(MAKE) --directory=./String/ release_clean
	$(MAKE) --directory=./Matcher/ release_clean
	$(MAKE) --directory=./AudioInfo/ release_clean
	$(MAKE) --directory=./Santa/ release_clean
	$(MAKE) --directory=./ArmyKnife/ release_clean
	$(MAKE) --directory=./FlipSideAE/ release_clean
	$(MAKE) --directory=./AudioInfo/ --makefile=MakefileTTE release_clean
	$(MAKE) --directory=./ArmyKnife/ --makefile=MakefileTTE release_clean
